version: '3.9'

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=django-insecure-dev-only-change-in-prod-bt%rxmfkspmft7meim7z=du$$0j%2zac00jtspia38$$80cd!0yn
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CORS_ALLOW_ALL_ORIGINS=True
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules    # anonymous volume so host node_modules don't override container
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - app

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data:
