"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.

This file controls:
- database configuration
- installed apps
- middleware
- security settings
- static files
"""

import os                           # Used to read environment variables
from pathlib import Path             # Used for filesystem paths


# --------------------------------------------------
# Base directory of the project
# --------------------------------------------------
# Example: /app/app/settings.py -> BASE_DIR = /app
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# SECURITY SETTINGS (DEV ONLY)
# --------------------------------------------------

# Secret key used for cryptographic signing
# ⚠️ NEVER hardcode this in production
SECRET_KEY = 'django-insecure-bt%rxmfkspmft7meim7z=du$0j%2zac00jtspia38$80cd!0yn'

# Debug mode (shows detailed error pages)
# ⚠️ Must be False in production
DEBUG = True

# Hosts/domain names Django can serve
# Empty means "only localhost" in dev
ALLOWED_HOSTS = []


# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------

# Apps enabled in this Django project
INSTALLED_APPS = [
    'django.contrib.admin',          # Admin panel
    'django.contrib.auth',           # Authentication system
    'django.contrib.contenttypes',   # Content type framework
    'django.contrib.sessions',       # Session management
    'django.contrib.messages',       # Flash messages
    'django.contrib.staticfiles',    # Static file handling
]


# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

# Middleware are layers that process requests/responses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',     # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --------------------------------------------------
# URL & TEMPLATE CONFIGURATION
# --------------------------------------------------

# Root URL configuration
ROOT_URLCONF = 'app.urls'

# Template engine settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],                   # Custom template directories
        'APP_DIRS': True,             # Look for templates inside apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Entry point for WSGI-compatible web servers
WSGI_APPLICATION = 'app.wsgi.application'


# --------------------------------------------------
# DATABASE CONFIGURATION (PostgreSQL)
# --------------------------------------------------
# Values come from environment variables set by Docker
# docker-compose.yml -> environment section

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',   # PostgreSQL backend
        'HOST': os.environ.get('DB_HOST'),           # Database host (Docker service name)
        'NAME': os.environ.get('DB_NAME'),           # Database name
        'USER': os.environ.get('DB_USER'),           # Database user
        'PASSWORD': os.environ.get('DB_PASS'),       # Database password
        # PORT not required (defaults to 5432)
    }
}


# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------
# Enforces secure passwords for users

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --------------------------------------------------
# INTERNATIONALIZATION & TIMEZONE
# --------------------------------------------------

LANGUAGE_CODE = 'en-us'   # Default language

TIME_ZONE = 'UTC'        # Server timezone

USE_I18N = True          # Enable translations
USE_L10N = True          # Locale-aware formatting
USE_TZ = True            # Use timezone-aware datetimes


# --------------------------------------------------
# STATIC FILES (CSS, JS, IMAGES)
# --------------------------------------------------

STATIC_URL = '/static/'  # URL path for static files


# --------------------------------------------------
# DEFAULT PRIMARY KEY TYPE
# --------------------------------------------------
# Default ID field for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
